AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS Fargate Services for AI Messaging Tool (using existing ALB, target groups, and log groups)'

Parameters:
  Environment:
    Type: String
    Default: 'production'
    AllowedValues: ['development', 'staging', 'production']
    Description: 'Environment name'

  VPCStackName:
    Type: String
    Default: 'ai-messaging-vpc'
    Description: 'Name of the VPC stack'

  DatabaseStackName:
    Type: String
    Default: 'ai-messaging-database'
    Description: 'Name of the database stack'

  CacheStackName:
    Type: String
    Default: 'ai-messaging-cache'
    Description: 'Name of the cache stack'

  StorageStackName:
    Type: String
    Default: 'ai-messaging-storage'
    Description: 'Name of the storage stack'

  ECRStackName:
    Type: String
    Default: 'ai-messaging-ecr'
    Description: 'Name of the ECR stack'

  ECSClusterName:
    Type: String
    Default: 'production-ai-messaging-cluster'
    Description: 'ECS Cluster Name'

  BackendImageTag:
    Type: String
    Default: 'latest'
    Description: 'Backend Docker image tag'

  FrontendImageTag:
    Type: String
    Default: 'latest'
    Description: 'Frontend Docker image tag'

  WorkerImageTag:
    Type: String
    Default: 'latest'
    Description: 'Worker Docker image tag'

  BackendCpu:
    Type: String
    Default: '1024'
    AllowedValues: ['256', '512', '1024', '2048', '4096']
    Description: 'Backend CPU units'

  BackendMemory:
    Type: String
    Default: '2048'
    AllowedValues: ['512', '1024', '2048', '4096', '8192']
    Description: 'Backend memory in MB'

  FrontendCpu:
    Type: String
    Default: '256'
    AllowedValues: ['256', '512', '1024', '2048', '4096']
    Description: 'Frontend CPU units'

  FrontendMemory:
    Type: String
    Default: '512'
    AllowedValues: ['512', '1024', '2048', '4096', '8192']
    Description: 'Frontend memory in MB'

  WorkerCpu:
    Type: String
    Default: '2048'
    AllowedValues: ['256', '512', '1024', '2048', '4096']
    Description: 'Worker CPU units'

  WorkerMemory:
    Type: String
    Default: '4096'
    AllowedValues: ['512', '1024', '2048', '4096', '8192']
    Description: 'Worker memory in MB'

  DesiredCount:
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 10
    Description: 'Desired number of tasks'

  MaxCount:
    Type: Number
    Default: 10
    MinValue: 1
    MaxValue: 50
    Description: 'Maximum number of tasks'

  MinCount:
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 10
    Description: 'Minimum number of tasks'

  TargetCpuUtilization:
    Type: Number
    Default: 70
    MinValue: 1
    MaxValue: 100
    Description: 'Target CPU utilization for auto scaling'

  TargetMemoryUtilization:
    Type: Number
    Default: 80
    MinValue: 1
    MaxValue: 100
    Description: 'Target memory utilization for auto scaling'

Conditions:
  IsProduction: !Equals [!Ref Environment, 'production']

Resources:
  # ECS Task Definitions
  BackendTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${Environment}-ai-messaging-backend-new'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: !Ref BackendCpu
      Memory: !Ref BackendMemory
      ExecutionRoleArn: !ImportValue
        Fn::Sub: '${Environment}-ai-messaging-ecr-task-role-arn'
      TaskRoleArn: !GetAtt TaskRole.Arn
      ContainerDefinitions:
        - Name: backend
          Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${Environment}-ai-messaging-backend:${BackendImageTag}'
          PortMappings:
            - ContainerPort: 8001
              Protocol: tcp
          Environment:
            - Name: NODE_ENV
              Value: !Ref Environment
            - Name: PORT
              Value: '8001'
            - Name: DB_HOST
              Value: !ImportValue
                Fn::Sub: '${Environment}-ai-messaging-db-endpoint'
            - Name: DB_PORT
              Value: !ImportValue
                Fn::Sub: '${Environment}-ai-messaging-db-port'
            - Name: DB_NAME
              Value: !ImportValue
                Fn::Sub: '${Environment}-ai-messaging-db-name'
            - Name: REDIS_HOST
              Value: !ImportValue
                Fn::Sub: '${Environment}-ai-messaging-cache-primary-endpoint'
            - Name: REDIS_PORT
              Value: !ImportValue
                Fn::Sub: '${Environment}-ai-messaging-cache-port'
            - Name: S3_BUCKET
              Value: !ImportValue
                Fn::Sub: '${Environment}-ai-messaging-uploads-bucket'
            - Name: DATABASE_URL
              Value: !Sub 
                - 'postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}'
                - DB_USER: !ImportValue
                    Fn::Sub: '${Environment}-ai-messaging-db-username'
                  DB_PASSWORD: !ImportValue
                    Fn::Sub: '${Environment}-ai-messaging-db-password'
                  DB_HOST: !ImportValue
                    Fn::Sub: '${Environment}-ai-messaging-db-endpoint'
                  DB_PORT: !ImportValue
                    Fn::Sub: '${Environment}-ai-messaging-db-port'
                  DB_NAME: !ImportValue
                    Fn::Sub: '${Environment}-ai-messaging-db-name'
            - Name: REDIS_URL
              Value: !Sub 
                - 'redis://${REDIS_HOST}:${REDIS_PORT}/0'
                - REDIS_HOST: !ImportValue
                    Fn::Sub: '${Environment}-ai-messaging-cache-primary-endpoint'
                  REDIS_PORT: !ImportValue
                    Fn::Sub: '${Environment}-ai-messaging-cache-port'
            - Name: GEMINI_API_KEY
              Value: 'AIzaSyAktRAFpxfniqX0ZCFswTNKQh59alVeSGY'
            - Name: SENDER_NAME
              Value: 'AI Messaging System'
            - Name: SENDER_EMAIL
              Value: 'admin@yourdomain.com'
            - Name: SENDER_PHONE
              Value: '+1-555-123-4567'
            - Name: MESSAGE_SUBJECT
              Value: 'Business Inquiry'
            - Name: COMPANY_NAME
              Value: 'Your Company'
            - Name: HOST
              Value: '0.0.0.0'
            - Name: TIMEOUT_PER_WEBSITE
              Value: '300'
            - Name: TIMEOUT_PER_BATCH
              Value: '900'
            - Name: TIMEOUT_PER_CHUNK
              Value: '600'
            - Name: QUEUE_TIMEOUT
              Value: '300'
            - Name: DB_POOL_TIMEOUT
              Value: '30'
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub '/aws/ecs/${Environment}-ai-messaging-backend'
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: backend
          HealthCheck:
            Command:
              - CMD-SHELL
              - curl -f http://localhost:8001/api/health || exit 1
            Interval: 30
            Timeout: 10
            Retries: 5
            StartPeriod: 120

  FrontendTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${Environment}-ai-messaging-frontend-new'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: !Ref FrontendCpu
      Memory: !Ref FrontendMemory
      ExecutionRoleArn: !ImportValue
        Fn::Sub: '${Environment}-ai-messaging-ecr-task-role-arn'
      TaskRoleArn: !GetAtt TaskRole.Arn
      ContainerDefinitions:
        - Name: frontend
          Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${Environment}-ai-messaging-frontend:${FrontendImageTag}'
          PortMappings:
            - ContainerPort: 3000
              Protocol: tcp
          Environment:
            - Name: NODE_ENV
              Value: !Ref Environment
            - Name: PORT
              Value: '3000'
            - Name: NEXT_PUBLIC_BACKEND_URL
              Value: !Sub 
                - 'http://${ALBDNS}:8000'
                - ALBDNS: !ImportValue
                    Fn::Sub: '${Environment}-ai-messaging-alb-dns'
            - Name: NEXT_PUBLIC_BASE_URL
              Value: !Sub 
                - 'http://${ALBDNS}:3000'
                - ALBDNS: !ImportValue
                    Fn::Sub: '${Environment}-ai-messaging-alb-dns'
            - Name: NEXTAUTH_URL
              Value: !Sub 
                - 'http://${ALBDNS}:3000'
                - ALBDNS: !ImportValue
                    Fn::Sub: '${Environment}-ai-messaging-alb-dns'
            - Name: NEXTAUTH_SECRET
              Value: 'your-secret-key-change-this-in-production'
            - Name: DATABASE_URL
              Value: !Sub 
                - 'postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}'
                - DB_USER: !ImportValue
                    Fn::Sub: '${Environment}-ai-messaging-db-username'
                  DB_PASSWORD: !ImportValue
                    Fn::Sub: '${Environment}-ai-messaging-db-password'
                  DB_HOST: !ImportValue
                    Fn::Sub: '${Environment}-ai-messaging-db-endpoint'
                  DB_PORT: !ImportValue
                    Fn::Sub: '${Environment}-ai-messaging-db-port'
                  DB_NAME: !ImportValue
                    Fn::Sub: '${Environment}-ai-messaging-db-name'
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub '/aws/ecs/${Environment}-ai-messaging-frontend'
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: frontend
          HealthCheck:
            Command:
              - CMD-SHELL
              - curl -f http://localhost:3000/ || exit 1
            Interval: 30
            Timeout: 5
            Retries: 3
            StartPeriod: 60

  WorkerTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${Environment}-ai-messaging-worker-new'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: !Ref WorkerCpu
      Memory: !Ref WorkerMemory
      ExecutionRoleArn: !ImportValue
        Fn::Sub: '${Environment}-ai-messaging-ecr-task-role-arn'
      TaskRoleArn: !GetAtt TaskRole.Arn
      ContainerDefinitions:
        - Name: worker
          Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${Environment}-ai-messaging-worker:${WorkerImageTag}'
          Environment:
            - Name: NODE_ENV
              Value: !Ref Environment
            - Name: DB_HOST
              Value: !ImportValue
                Fn::Sub: '${Environment}-ai-messaging-db-endpoint'
            - Name: DB_PORT
              Value: !ImportValue
                Fn::Sub: '${Environment}-ai-messaging-db-port'
            - Name: DB_NAME
              Value: !ImportValue
                Fn::Sub: '${Environment}-ai-messaging-db-name'
            - Name: REDIS_HOST
              Value: !ImportValue
                Fn::Sub: '${Environment}-ai-messaging-cache-primary-endpoint'
            - Name: REDIS_PORT
              Value: !ImportValue
                Fn::Sub: '${Environment}-ai-messaging-cache-port'
            - Name: S3_BUCKET
              Value: !ImportValue
                Fn::Sub: '${Environment}-ai-messaging-uploads-bucket'
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub '/aws/ecs/${Environment}-ai-messaging-worker'
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: worker

  # ECS Services
  BackendService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub '${Environment}-ai-messaging-backend-service-new'
      Cluster: !ImportValue
        Fn::Sub: '${Environment}-ai-messaging-cluster-name'
      TaskDefinition: !Ref BackendTaskDefinition
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - !ImportValue
              Fn::Sub: '${Environment}-ai-messaging-app-sg-id'
          Subnets:
            - !ImportValue
              Fn::Sub: '${Environment}-ai-messaging-private-subnet-1-id'
            - !ImportValue
              Fn::Sub: '${Environment}-ai-messaging-private-subnet-2-id'
          AssignPublicIp: DISABLED
      LoadBalancers:
        - ContainerName: backend
          ContainerPort: 8001
          TargetGroupArn: !ImportValue
            Fn::Sub: '${Environment}-backend-tg-arn'
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-ai-messaging-backend-service-new'

  FrontendService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub '${Environment}-ai-messaging-frontend-service-new'
      Cluster: !ImportValue
        Fn::Sub: '${Environment}-ai-messaging-cluster-name'
      TaskDefinition: !Ref FrontendTaskDefinition
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - !ImportValue
              Fn::Sub: '${Environment}-ai-messaging-web-sg-id'
          Subnets:
            - !ImportValue
              Fn::Sub: '${Environment}-ai-messaging-public-subnet-1-id'
            - !ImportValue
              Fn::Sub: '${Environment}-ai-messaging-public-subnet-2-id'
          AssignPublicIp: ENABLED
      LoadBalancers:
        - ContainerName: frontend
          ContainerPort: 3000
          TargetGroupArn: !ImportValue
            Fn::Sub: '${Environment}-frontend-tg-arn'
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-ai-messaging-frontend-service-new'

  WorkerService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub '${Environment}-ai-messaging-worker-service-new'
      Cluster: !ImportValue
        Fn::Sub: '${Environment}-ai-messaging-cluster-name'
      TaskDefinition: !Ref WorkerTaskDefinition
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - !ImportValue
              Fn::Sub: '${Environment}-ai-messaging-app-sg-id'
          Subnets:
            - !ImportValue
              Fn::Sub: '${Environment}-ai-messaging-private-subnet-1-id'
            - !ImportValue
              Fn::Sub: '${Environment}-ai-messaging-private-subnet-2-id'
          AssignPublicIp: DISABLED
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-ai-messaging-worker-service-new'

  # IAM Role for ECS Tasks
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !ImportValue
                    Fn::Sub: '${Environment}-ai-messaging-uploads-bucket-arn'
                  - !Sub 
                    - '${BucketArn}/*'
                    - BucketArn: !ImportValue
                        Fn::Sub: '${Environment}-ai-messaging-uploads-bucket-arn'
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: '*'
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-ai-messaging-task-role-new'

  # Auto Scaling
  BackendScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn: BackendService
    Properties:
      MaxCapacity: !Ref MaxCount
      MinCapacity: !Ref MinCount
      ResourceId: !Sub 'service/${ECSClusterName}/${Environment}-ai-messaging-backend-service-new'
      RoleARN: !Sub 'arn:aws:iam::${AWS::AccountId}:role/aws-service-role/ecs.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_ECSService'
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  BackendScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub '${Environment}-ai-messaging-backend-scaling-new'
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref BackendScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: !Ref TargetCpuUtilization
        ScaleOutCooldown: 300
        ScaleInCooldown: 300
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization

  WorkerScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn: WorkerService
    Properties:
      MaxCapacity: !Ref MaxCount
      MinCapacity: !Ref MinCount
      ResourceId: !Sub 'service/${ECSClusterName}/${Environment}-ai-messaging-worker-service-new'
      RoleARN: !Sub 'arn:aws:iam::${AWS::AccountId}:role/aws-service-role/ecs.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_ECSService'
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  WorkerScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub '${Environment}-ai-messaging-worker-scaling-new'
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref WorkerScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: !Ref TargetCpuUtilization
        ScaleOutCooldown: 300
        ScaleInCooldown: 300
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization

Outputs:
  BackendServiceName:
    Description: 'Backend Service Name'
    Value: !Ref BackendService
    Export:
      Name: !Sub '${Environment}-ai-messaging-backend-service-name-new'

  FrontendServiceName:
    Description: 'Frontend Service Name'
    Value: !Ref FrontendService
    Export:
      Name: !Sub '${Environment}-ai-messaging-frontend-service-name-new'

  WorkerServiceName:
    Description: 'Worker Service Name'
    Value: !Ref WorkerService
    Export:
      Name: !Sub '${Environment}-ai-messaging-worker-service-name-new'

  TaskRoleArn:
    Description: 'Task Role ARN'
    Value: !GetAtt TaskRole.Arn
    Export:
      Name: !Sub '${Environment}-ai-messaging-task-role-arn-new'
