AWSTemplateFormatVersion: '2010-09-09'
Description: 'ElastiCache Redis Cluster for AI Messaging Tool'

Parameters:
  Environment:
    Type: String
    Default: 'production'
    AllowedValues: ['development', 'staging', 'production']
    Description: 'Environment name'

  VPCStackName:
    Type: String
    Default: 'ai-messaging-vpc'
    Description: 'Name of the VPC stack'

  NodeType:
    Type: String
    Default: 'cache.t3.micro'
    AllowedValues: ['cache.t3.micro', 'cache.t3.small', 'cache.t3.medium', 'cache.t3.large']
    Description: 'Cache node type'

  NumCacheNodes:
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 6
    Description: 'Number of cache nodes'

  EngineVersion:
    Type: String
    Default: '7.0'
    AllowedValues: ['6.0', '6.2', '6.x', '7.0']
    Description: 'Redis engine version'

  Port:
    Type: Number
    Default: 6379
    MinValue: 1024
    MaxValue: 65535
    Description: 'Redis port'

  ParameterGroupFamily:
    Type: String
    Default: 'redis7.x'
    AllowedValues: ['redis6.x', 'redis7.x']
    Description: 'Parameter group family'

  SnapshotRetentionLimit:
    Type: Number
    Default: 5
    MinValue: 0
    MaxValue: 35
    Description: 'Snapshot retention limit in days'

  SnapshotWindow:
    Type: String
    Default: '03:00-05:00'
    Description: 'Snapshot window (UTC)'

  MaintenanceWindow:
    Type: String
    Default: 'sun:05:00-sun:07:00'
    Description: 'Maintenance window (UTC)'

  AutomaticFailoverEnabled:
    Type: String
    Default: 'false'
    AllowedValues: ['true', 'false']
    Description: 'Enable automatic failover'

  MultiAZEnabled:
    Type: String
    Default: 'false'
    AllowedValues: ['true', 'false']
    Description: 'Enable Multi-AZ'

Conditions:
  IsProduction: !Equals [!Ref Environment, 'production']
  IsMultiAZ: !Equals [!Ref MultiAZEnabled, 'true']
  IsAutoFailover: !Equals [!Ref AutomaticFailoverEnabled, 'true']

Resources:
  # Subnet Group
  CacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: 'Subnet group for AI Messaging Tool Redis cluster'
      SubnetIds:
        - !ImportValue
          Fn::Sub: '${VPCStackName}-ai-messaging-private-subnet-1-id'
        - !ImportValue
          Fn::Sub: '${VPCStackName}-ai-messaging-private-subnet-2-id'
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-ai-messaging-cache-subnet-group'

  # Parameter Group
  CacheParameterGroup:
    Type: AWS::ElastiCache::ParameterGroup
    Properties:
      CacheParameterGroupFamily: !Ref ParameterGroupFamily
      Description: 'Parameter group for AI Messaging Tool Redis'
      Properties:
        maxmemory-policy: allkeys-lru
        timeout: 300
        tcp-keepalive: 60
        tcp-backlog: 511
        maxmemory-samples: 5
        slowlog-log-slower-than: 10000
        slowlog-max-len: 128
        notify-keyspace-events: Ex
        hash-max-ziplist-entries: 512
        hash-max-ziplist-value: 64
        list-max-ziplist-size: -2
        list-compress-depth: 0
        set-max-intset-entries: 512
        zset-max-ziplist-entries: 128
        zset-max-ziplist-value: 64
        hll-sparse-max-bytes: 3000
        stream-node-max-bytes: 4096
        stream-node-max-entries: 100
        activerehashing: yes
        client-output-buffer-limit-normal: 0 0 0
        client-output-buffer-limit-replica: 256mb 64mb 60
        client-output-buffer-limit-pubsub: 32mb 8mb 60
        hz: 10
        dynamic-hz: yes
        aof-rewrite-incremental-fsync: yes
        rdb-save-incremental-fsync: yes
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-ai-messaging-cache-params'

  # Security Group
  CacheSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${Environment}-ai-messaging-cache-sg'
      GroupDescription: 'Security group for Redis cache'
      VpcId: !ImportValue
        Fn::Sub: '${VPCStackName}-ai-messaging-vpc-id'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref Port
          ToPort: !Ref Port
          SourceSecurityGroupId: !ImportValue
            Fn::Sub: '${VPCStackName}-ai-messaging-app-sg-id'
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-ai-messaging-cache-sg'

  # Replication Group (Cluster)
  CacheReplicationGroup:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      ReplicationGroupId: !Sub '${Environment}-ai-messaging-redis'
      Description: 'Redis cluster for AI Messaging Tool'
      NodeType: !Ref NodeType
      Port: !Ref Port
      ParameterGroupName: !Ref CacheParameterGroup
      CacheSubnetGroupName: !Ref CacheSubnetGroup
      SecurityGroupIds:
        - !Ref CacheSecurityGroup
      Engine: redis
      EngineVersion: !Ref EngineVersion
      NumCacheClusters: !If [IsMultiAZ, 2, !Ref NumCacheNodes]
      AutomaticFailoverEnabled: !If [IsAutoFailover, true, false]
      MultiAZEnabled: !If [IsMultiAZ, true, false]
      AtRestEncryptionEnabled: true
      TransitEncryptionEnabled: true
      AuthToken: !Sub '${Environment}-ai-messaging-redis-token-${RandomString}'
      SnapshotRetentionLimit: !Ref SnapshotRetentionLimit
      SnapshotWindow: !Ref SnapshotWindow
      PreferredMaintenanceWindow: !Ref MaintenanceWindow
      LogDeliveryConfigurations:
        - DestinationType: cloudwatch-logs
          LogFormat: text
          LogType: slow-log
        - DestinationType: cloudwatch-logs
          LogFormat: json
          LogType: engine-log
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-ai-messaging-redis'
        - Key: Environment
          Value: !Ref Environment

  # Random String for Auth Token
  RandomString:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt RandomStringFunction.Arn
      Length: 16

  # Lambda Function for Random String Generation
  RandomStringFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${Environment}-ai-messaging-random-string'
      Runtime: python3.9
      Handler: index.lambda_handler
      Role: !GetAtt RandomStringRole.Arn
      Code:
        ZipFile: |
          import json
          import random
          import string
          import boto3
          import cfnresponse
          
          def lambda_handler(event, context):
              try:
                  length = int(event['ResourceProperties']['Length'])
                  random_string = ''.join(random.choices(string.ascii_letters + string.digits, k=length))
                  
                  response_data = {
                      'RandomString': random_string
                  }
                  
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, response_data)
              except Exception as e:
                  cfnresponse.send(event, context, cfnresponse.FAILED, {'Error': str(e)})

  # IAM Role for Random String Lambda
  RandomStringRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  # CloudWatch Log Group for Redis
  CacheLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/elasticache/redis/${Environment}-ai-messaging-redis'
      RetentionInDays: !If [IsProduction, 30, 7]
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-ai-messaging-cache-logs'

Outputs:
  CacheReplicationGroupId:
    Description: 'Cache Replication Group ID'
    Value: !Ref CacheReplicationGroup
    Export:
      Name: !Sub '${Environment}-ai-messaging-cache-replication-group-id'

  CachePrimaryEndpoint:
    Description: 'Cache Primary Endpoint'
    Value: !GetAtt CacheReplicationGroup.RedisEndpoint.Address
    Export:
      Name: !Sub '${Environment}-ai-messaging-cache-primary-endpoint'

  CachePort:
    Description: 'Cache Port'
    Value: !Ref Port
    Export:
      Name: !Sub '${Environment}-ai-messaging-cache-port'

  CacheReaderEndpoint:
    Description: 'Cache Reader Endpoint'
    Value: !GetAtt CacheReplicationGroup.RedisEndpoint.Address
    Export:
      Name: !Sub '${Environment}-ai-messaging-cache-reader-endpoint'

  CacheSecurityGroupId:
    Description: 'Cache Security Group ID'
    Value: !Ref CacheSecurityGroup
    Export:
      Name: !Sub '${Environment}-ai-messaging-cache-sg-id'

  CacheSubnetGroupName:
    Description: 'Cache Subnet Group Name'
    Value: !Ref CacheSubnetGroup
    Export:
      Name: !Sub '${Environment}-ai-messaging-cache-subnet-group-name'
