import os

# Celery Configuration Variables
CELERY_WORKERS = 4
CELERY_CONCURRENCY = 8
CELERY_MAX_TASKS_PER_CHILD = 1000
CELERY_TASK_TIME_LIMIT = 1800
CELERY_TASK_SOFT_TIME_LIMIT = 1500
CELERY_TASK_MAX_RETRIES = 3
CELERY_TASK_RETRY_DELAY = 60
