module.exports = {
  apps: [
    {
      name: 'fastapi-backend',
      script: 'venv/bin/uvicorn',
      args: 'main:app --host 0.0.0.0 --port 8001 --workers 4',
      cwd: '/var/www/ai-messaging-tool/Automated-AI-Messaging-Tool-Backend',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1024M',
      exec_mode: 'fork',
      interpreter: 'none',
      restart_delay: 2000,
      max_restarts: 5,
      min_uptime: '5s',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: 'postgresql://postgres:AiMessaging2024Secure@production-ai-messaging-db.cmpkwkuqu30h.us-east-1.rds.amazonaws.com:5432/ai_messaging',
        REDIS_URL: 'redis://localhost:6379/0',
        GEMINI_API_KEY: 'AIzaSyANDNgkwSUbg5xXyGYIJIcs2W-REhNjk6I',
        TESTING_MODE_ENABLED: 'false',
        MAX_AI_MESSAGES_PER_FILE: '30',
        PYTHON_API_URL: 'http://98.85.16.204:8001',
        PYTHONUNBUFFERED: '1',
        OMP_NUM_THREADS: '4',
        MKL_NUM_THREADS: '4'
      },
      error_file: './logs/fastapi-error.log',
      out_file: './logs/fastapi-out.log',
      log_file: './logs/fastapi-combined.log',
      time: true
    },
    {
      name: 'celery-scraper-1',
      script: 'venv/bin/celery',
      args: '-A celery_app worker --loglevel=warning --concurrency=4 --queues=scraping,file_processing --hostname=scraper1@%h --max-tasks-per-child=200 --prefetch-multiplier=2',
      cwd: '/var/www/ai-messaging-tool/Automated-AI-Messaging-Tool-Backend',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1024M',
      interpreter: 'none',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: 'postgresql://postgres:AiMessaging2024Secure@production-ai-messaging-db.cmpkwkuqu30h.us-east-1.rds.amazonaws.com:5432/ai_messaging',
        REDIS_URL: 'redis://localhost:6379/0',
        GEMINI_API_KEY: 'AIzaSyANDNgkwSUbg5xXyGYIJIcs2W-REhNjk6I',
        TESTING_MODE_ENABLED: 'false',
        MAX_AI_MESSAGES_PER_FILE: '30',
        PYTHON_API_URL: 'http://98.85.16.204:8001',
        PYTHONUNBUFFERED: '1',
        OMP_NUM_THREADS: '1',
        MKL_NUM_THREADS: '1'
      },
      error_file: './logs/celery-scraper-1-error.log',
      out_file: './logs/celery-scraper-1-out.log',
      log_file: './logs/celery-scraper-1-combined.log',
      time: true,
      restart_delay: 2000,
      max_restarts: 5,
      min_uptime: '5s'
    },
    {
      name: 'celery-scraper-2',
      script: 'venv/bin/celery',
      args: '-A celery_app worker --loglevel=warning --concurrency=4 --queues=scraping,file_processing --hostname=scraper2@%h --max-tasks-per-child=200 --prefetch-multiplier=2',
      cwd: '/var/www/ai-messaging-tool/Automated-AI-Messaging-Tool-Backend',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1024M',
      interpreter: 'none',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: 'postgresql://postgres:AiMessaging2024Secure@production-ai-messaging-db.cmpkwkuqu30h.us-east-1.rds.amazonaws.com:5432/ai_messaging',
        REDIS_URL: 'redis://localhost:6379/0',
        GEMINI_API_KEY: 'AIzaSyANDNgkwSUbg5xXyGYIJIcs2W-REhNjk6I',
        TESTING_MODE_ENABLED: 'false',
        MAX_AI_MESSAGES_PER_FILE: '30',
        PYTHON_API_URL: 'http://98.85.16.204:8001',
        PYTHONUNBUFFERED: '1',
        OMP_NUM_THREADS: '1',
        MKL_NUM_THREADS: '1'
      },
      error_file: './logs/celery-scraper-2-error.log',
      out_file: './logs/celery-scraper-2-out.log',
      log_file: './logs/celery-scraper-2-combined.log',
      time: true,
      restart_delay: 2000,
      max_restarts: 5,
      min_uptime: '5s'
    },
    {
      name: 'celery-ai-1',
      script: 'venv/bin/celery',
      args: '-A celery_app worker --loglevel=warning --concurrency=3 --queues=ai_processing,default --hostname=ai1@%h --max-tasks-per-child=150 --prefetch-multiplier=1',
      cwd: '/var/www/ai-messaging-tool/Automated-AI-Messaging-Tool-Backend',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1536M',
      interpreter: 'none',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: 'postgresql://postgres:AiMessaging2024Secure@production-ai-messaging-db.cmpkwkuqu30h.us-east-1.rds.amazonaws.com:5432/ai_messaging',
        REDIS_URL: 'redis://localhost:6379/0',
        GEMINI_API_KEY: 'AIzaSyANDNgkwSUbg5xXyGYIJIcs2W-REhNjk6I',
        TESTING_MODE_ENABLED: 'false',
        MAX_AI_MESSAGES_PER_FILE: '30',
        PYTHON_API_URL: 'http://98.85.16.204:8001',
        PYTHONUNBUFFERED: '1',
        OMP_NUM_THREADS: '1',
        MKL_NUM_THREADS: '1'
      },
      error_file: './logs/celery-ai-1-error.log',
      out_file: './logs/celery-ai-1-out.log',
      log_file: './logs/celery-ai-1-combined.log',
      time: true,
      restart_delay: 2000,
      max_restarts: 5,
      min_uptime: '5s'
    },
    {
      name: 'celery-ai-2',
      script: 'venv/bin/celery',
      args: '-A celery_app worker --loglevel=warning --concurrency=3 --queues=ai_processing,default --hostname=ai2@%h --max-tasks-per-child=150 --prefetch-multiplier=1',
      cwd: '/var/www/ai-messaging-tool/Automated-AI-Messaging-Tool-Backend',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1536M',
      interpreter: 'none',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: 'postgresql://postgres:AiMessaging2024Secure@production-ai-messaging-db.cmpkwkuqu30h.us-east-1.rds.amazonaws.com:5432/ai_messaging',
        REDIS_URL: 'redis://localhost:6379/0',
        GEMINI_API_KEY: 'AIzaSyANDNgkwSUbg5xXyGYIJIcs2W-REhNjk6I',
        TESTING_MODE_ENABLED: 'false',
        MAX_AI_MESSAGES_PER_FILE: '30',
        PYTHON_API_URL: 'http://98.85.16.204:8001',
        PYTHONUNBUFFERED: '1',
        OMP_NUM_THREADS: '1',
        MKL_NUM_THREADS: '1'
      },
      error_file: './logs/celery-ai-2-error.log',
      out_file: './logs/celery-ai-2-out.log',
      log_file: './logs/celery-ai-2-combined.log',
      time: true,
      restart_delay: 2000,
      max_restarts: 5,
      min_uptime: '5s'
    },
    {
      name: 'celery-priority',
      script: 'venv/bin/celery',
      args: '-A celery_app worker --loglevel=warning --concurrency=2 --queues=priority,urgent --hostname=priority@%h --max-tasks-per-child=100 --prefetch-multiplier=1',
      cwd: '/var/www/ai-messaging-tool/Automated-AI-Messaging-Tool-Backend',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      interpreter: 'none',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: 'postgresql://postgres:AiMessaging2024Secure@production-ai-messaging-db.cmpkwkuqu30h.us-east-1.rds.amazonaws.com:5432/ai_messaging',
        REDIS_URL: 'redis://localhost:6379/0',
        GEMINI_API_KEY: 'AIzaSyANDNgkwSUbg5xXyGYIJIcs2W-REhNjk6I',
        TESTING_MODE_ENABLED: 'false',
        MAX_AI_MESSAGES_PER_FILE: '30',
        PYTHON_API_URL: 'http://98.85.16.204:8001',
        PYTHONUNBUFFERED: '1',
        OMP_NUM_THREADS: '1',
        MKL_NUM_THREADS: '1'
      },
      error_file: './logs/celery-priority-error.log',
      out_file: './logs/celery-priority-out.log',
      log_file: './logs/celery-priority-combined.log',
      time: true,
      restart_delay: 2000,
      max_restarts: 5,
      min_uptime: '5s'
    }
  ]
};
