#!/bin/bash
# Upload Configuration for Backend Project
# Generated by setup-ssh-keys.sh

export SERVER_HOST="103.215.159.51"
export SERVER_USER="xb3353"
export SERVER_PATH="/home/xb3353/Automated-AI-Messaging-Tool-Backend"
export SSH_KEY_PATH="/Users/apple/.ssh/backend_upload_key"
export SSH_HOST_ALIAS="backend-server"

# Backend service configuration
export BACKEND_PORT="8000"
export BACKEND_SERVICE_NAME="ai-messaging-backend"

# Upload directories
export UPLOAD_STAGING_DIR="toUpload"
export UPLOAD_BACKUP_DIR="uploadBackups"

# File patterns to upload
export PYTHON_FILES="*.py"
export CONFIG_FILES="*.txt *.yml *.yaml *.json *.env*"
export REQUIREMENT_FILES="requirements*.txt"
export SHELL_FILES="*.sh"

echo "✅ Upload configuration loaded"
